import Foundation

// MARK: - CW keyer (Phase 4.2)

extension RigController {

    /// Sets the CW keyer speed in words per minute.
    ///
    /// Most radios accept 6–48 WPM in discrete steps; values outside
    /// that range are clamped on ``CWSpeed`` construction.
    ///
    /// - Throws: ``RigError/notConnected`` if not connected,
    ///   ``RigError/unsupportedOperation(_:)`` if the radio does
    ///   not expose a CW keyer (see ``RigCapabilities/supportsCWKeyer``).
    public func setCWSpeed(_ speed: CWSpeed) async throws {
        try requireConnected()
        let p = try requireTrait((any SupportsCWKeyer).self, named: "CW keyer speed")
        try await p.setCWSpeed(speed)
    }

    /// Reads the current CW keyer speed.
    ///
    /// - Throws: ``RigError/notConnected``,
    ///   ``RigError/unsupportedOperation(_:)``.
    public func cwSpeed() async throws -> CWSpeed {
        try requireConnected()
        let p = try requireTrait((any SupportsCWKeyer).self, named: "CW keyer speed")
        return try await p.getCWSpeed()
    }

    /// Sets the CW sidetone pitch in Hz.
    ///
    /// Most radios accept 300–900 Hz; values outside that range are
    /// clamped on ``CWPitch`` construction.
    ///
    /// - Throws: ``RigError/notConnected``,
    ///   ``RigError/unsupportedOperation(_:)``.
    public func setCWPitch(_ pitch: CWPitch) async throws {
        try requireConnected()
        let p = try requireTrait((any SupportsCWKeyer).self, named: "CW pitch")
        try await p.setCWPitch(pitch)
    }

    /// Reads the current CW sidetone pitch.
    ///
    /// - Throws: ``RigError/notConnected``,
    ///   ``RigError/unsupportedOperation(_:)``.
    public func cwPitch() async throws -> CWPitch {
        try requireConnected()
        let p = try requireTrait((any SupportsCWKeyer).self, named: "CW pitch")
        return try await p.getCWPitch()
    }

    /// Sets the break-in mode (off / semi / full).
    ///
    /// - Throws: ``RigError/notConnected``,
    ///   ``RigError/unsupportedOperation(_:)``.
    public func setBreakIn(_ mode: BreakInMode) async throws {
        try requireConnected()
        let p = try requireTrait((any SupportsCWKeyer).self, named: "Break-in")
        try await p.setBreakIn(mode)
    }

    /// Reads the current break-in mode.
    ///
    /// - Throws: ``RigError/notConnected``,
    ///   ``RigError/unsupportedOperation(_:)``.
    public func breakIn() async throws -> BreakInMode {
        try requireConnected()
        let p = try requireTrait((any SupportsCWKeyer).self, named: "Break-in")
        return try await p.getBreakIn()
    }

    /// Sends a CW message generated by the radio's internal keyer.
    ///
    /// Most Icom radios cap the message at 30 ASCII characters;
    /// longer strings are truncated silently. Non-ASCII characters
    /// are stripped — the radio would reject them anyway.
    ///
    /// - Parameter text: ASCII message to send.
    /// - Throws: ``RigError/notConnected``,
    ///   ``RigError/unsupportedOperation(_:)`` if the radio does not
    ///   support text→CW generation (see
    ///   ``RigCapabilities/supportsSendCW``).
    public func sendCW(_ text: String) async throws {
        try requireConnected()
        let p = try requireTrait((any SupportsSendCW).self, named: "CW text send")
        try await p.sendCW(text)
    }

    /// Aborts any CW transmission currently in progress.
    /// Safe to call even when nothing is sending.
    ///
    /// - Throws: ``RigError/notConnected``,
    ///   ``RigError/unsupportedOperation(_:)``.
    public func stopCW() async throws {
        try requireConnected()
        let p = try requireTrait((any SupportsSendCW).self, named: "CW text send")
        try await p.stopCW()
    }

    /// Internal: shared guard reused across the CW accessors.
    private func requireConnected() throws {
        guard connected else { throw RigError.notConnected }
    }
}
